package com.deviljelly.terminalj.terminal.codepage;

public class ASCII {

	public static final byte ESC = 0x1b;
	
	public static final byte ZERO = 0x30;
	public static final byte ONE = 0x31;
	public static final byte TWO = 0x32;
	public static final byte THREE = 0x33;
	public static final byte FOUR = 0x34;
	public static final byte FIVE = 0x35;
	public static final byte SIX = 0x36;
	public static final byte SEVEN = 0x37;
	public static final byte EIGHT = 0x38;
	public static final byte NINE = 0x39;
	public static final byte SEMI_COLON = 0x3b;
	public static final byte QUESTION_MARK = 0x3f;
	public static final byte CAPITAL_A = 0x41;	
	public static final byte CAPITAL_B = 0x42;	
	public static final byte CAPITAL_C = 0x43;	
	public static final byte CAPITAL_D = 0x44;	
	public static final byte CAPITAL_E = 0x45;	
	public static final byte CAPITAL_F = 0x46;	
	public static final byte CAPITAL_G = 0x47;	
	public static final byte CAPITAL_H = 0x48;	
	public static final byte CAPITAL_I = 0x48;	
	public static final byte CAPITAL_J = 0x4A;	
	public static final byte CAPITAL_K = 0x4B;	
	public static final byte CAPITAL_L = 0x4C;	
	public static final byte CAPITAL_M = 0x4D;	
	public static final byte CAPITAL_N = 0x4E;	
	public static final byte CAPITAL_O = 0x4F;	
	public static final byte CAPITAL_P = 0x50;	
	public static final byte CAPITAL_Q = 0x51;	
	public static final byte CAPITAL_R = 0x52;	
	public static final byte CAPITAL_S = 0x53;	
	public static final byte CAPITAL_T = 0x54;	
	public static final byte CAPITAL_U = 0x55;	
	public static final byte CAPITAL_V = 0x56;	
	public static final byte CAPITAL_W = 0x57;	
	public static final byte CAPITAL_X = 0x58;	
	public static final byte CAPITAL_Y = 0x59;	
	public static final byte CAPITAL_Z = 0x5A;	
	public static final byte LEFT_SQUARE_BRACKET = 0x5b;
	public static final byte LOWER_CASE_A = 0x61;
	public static final byte LOWER_CASE_B = 0x62;
	public static final byte LOWER_CASE_C = 0x63;
	public static final byte LOWER_CASE_D = 0x64;
	public static final byte LOWER_CASE_E = 0x65;
	public static final byte LOWER_CASE_F = 0x66;
	public static final byte LOWER_CASE_G = 0x67;
	public static final byte LOWER_CASE_H = 0x68;
	public static final byte LOWER_CASE_I = 0x69;
	public static final byte LOWER_CASE_J = 0x6A;
	public static final byte LOWER_CASE_K = 0x6B;
	public static final byte LOWER_CASE_L = 0x6C;
	public static final byte LOWER_CASE_M = 0x6d;
	public static final byte LOWER_CASE_N = 0x6e;
	public static final byte LOWER_CASE_O = 0x6f;
	public static final byte LOWER_CASE_P = 0x70;
	public static final byte LOWER_CASE_Q = 0x71;
	public static final byte LOWER_CASE_R = 0x72;
	public static final byte LOWER_CASE_S = 0x73;
	public static final byte LOWER_CASE_T = 0x74;
	public static final byte LOWER_CASE_U = 0x75;
	public static final byte LOWER_CASE_V = 0x76;
	public static final byte LOWER_CASE_W = 0x77;
	public static final byte LOWER_CASE_X = 0x78;
	public static final byte LOWER_CASE_Y = 0x79;
	public static final byte LOWER_CASE_Z = 0x7A;
	
}
